# Data Science Pandas

## Tasks Today:

0) <b>Pre-Work</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) Numpy Random Sampling

1) <b>Pandas</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) Importing <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) Tabular Data Structures <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - from_dict() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - read_csv() <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) <b>In-Class Exercise #1</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; d) Accessing Data <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Indexing <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - df.loc <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - keys() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Slicing a DataFrame <br>
 &nbsp;&nbsp;&nbsp;&nbsp; e) Built-In Methods <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - head() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - tail() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - shape <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - describe() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - sort_values() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - .columns <br>
 &nbsp;&nbsp;&nbsp;&nbsp; f) <b>In-Class Exercise #2</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; g) Filtration <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Conditionals <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Subsetting <br>
 &nbsp;&nbsp;&nbsp;&nbsp; h) Column Transformations <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Generating a New Column w/Data <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - User Defined Function <br>
 &nbsp;&nbsp;&nbsp;&nbsp; i) Aggregations <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - groupby() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Type of groupby() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - mean() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - groupby() w/Multiple Columns <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - drop_duplicates() <br>

## Numpy Random Sampling

In [ ]:
%pip install numpy

Collecting numpyNote: you may need to restart the kernel to use updated packages.

  Downloading numpy-1.26.2-cp310-cp310-win_amd64.whl (15.8 MB)
     ---------------------------------------- 15.8/15.8 MB 9.5 MB/s eta 0:00:00
Installing collected packages: numpy
Successfully installed numpy-1.26.2

  WARNING: The script f2py.exe is installed in 'c:\Users\syeda\AppData\Local\Programs\Python\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip available: 22.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
import numpy as np
a=np.random.rand(5)
b=np.random.randn(6)
c=np.random.randint(3,5)
print(a)
print(b)
print(c)

[0.39664088 0.93209206 0.67770772 0.35227119 0.27058768]
[-1.77822956 -1.63459855 -1.14368051 -0.50012039  1.00716372  1.91986147]
3

## Pandas <br>

<p>Pandas is a flexible data analysis library built on top of NumPy that is excellent for working with tabular data. It is currently the de-facto standard for Python-based data analysis, and fluency in Pandas will do wonders for your productivity and frankly your resume. It is one of the fastest ways of getting from zero to answer in existence. </p>

<ul>
    <li>Pandas is a Python module, written in C. The Pandas module is a high performance, highly efficient, and high level data analysis library. It allows us to work with large sets of data called dataframes.</li>
    <li>Series is a one-dimensional labeled array capable of holding data of any type (integer, string, float, python objects, etc.)</li>
    <li>Dataframe = Spreadsheet (has column headers, index, etc.)</li>
</ul>

### Importing

In [ ]:
%pip install pandas

Collecting pandas
  Downloading pandas-2.1.4-cp310-cp310-win_amd64.whl (10.7 MB)
     --------------------------------------- 10.7/10.7 MB 21.9 MB/s eta 0:00:00
Collecting pytz>=2020.1
  Downloading pytz-2023.3.post1-py2.py3-none-any.whl (502 kB)
     ------------------------------------- 502.5/502.5 kB 30.8 MB/s eta 0:00:00
Requirement already satisfied: numpy<2,>=1.22.4 in c:\users\syeda\appdata\local\programs\python\python310\lib\site-packages (from pandas) (1.26.2)
Collecting tzdata>=2022.1
  Downloading tzdata-2023.3-py2.py3-none-any.whl (341 kB)
     ------------------------------------- 341.8/341.8 kB 20.7 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\syeda\appdata\roaming\python\python310\site-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\syeda\appdata\roaming\python\python310\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Installing collected packages: pytz, tzdata, pandas
Successfully installed pandas-2.1.4 pytz-2023.3.post1 tzdata-2023.3
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
import pandas as pd

### Tabular data structures <br>
<p>The central object of study in Pandas is the DataFrame, which is a tabular data structure with rows and columns like an excel spreadsheet. The first point of discussion is the creation of dataframes both from native Python dictionaries, and text files through the Pandas I/O system.</p>

In [ ]:

d={'sports1':['cricket', 'Baseball', 'Tennis','icehockey','soccer','golf','watersports'],
    'players':['james','adam','john','laura','angie','alice','rebbeca']}
df=pd.DataFrame(d)
print(df)

       sports1  players
0      cricket    james
1     Baseball     adam
2       Tennis     john
3    icehockey    laura
4       soccer    angie
5         golf    alice
6  watersports  rebbeca

##### from_dict()

<p>Let's convert our not-so-useful-for-analysis dict into a Pandas dataframe. We can use the from_dict function to do this easily using Pandas:</p>

In [ ]:
pd.DataFrame.from_dict(d)

       sports1  players
0      cricket    james
1     Baseball     adam
2       Tennis     john
3    icehockey    laura
4       soccer    angie
5         golf    alice
6  watersports  rebbeca

##### read_csv()

In [ ]:
# pd.set_option('display.max_columns', None)
# pd.set_option('display.max_rows', None)

### In-Class Exercise #1 - Read in Boston Red Sox Hitting Data <br>
<p>Use the pandas read_csv() method to read in the statistics from the two files yesterday.</p>

In [ ]:
import warnings
warnings.filterwarnings('ignore')
df1=pd.read_csv('/content/redsox_2018_hitting.csv',delimiter='\,')
df2=pd.read_csv('/content/redsox_2017_hitting_1.csv',delimiter='\,')

### Accessing Data <br>

##### Indexing

<p>You can directly select a column of a dataframe just like you would a dict. The result is a Pandas 'Series' object.</p>

In [ ]:
df1['SLG']

0     0.279
1     0.433
2     0.388
3     0.522
4     0.433
5     0.465
6     0.403
7     0.640
8     0.629
9     0.411
10    0.283
11    0.328
12    0.395
13    0.507
14    0.311
15    0.415
16    0.389
17    0.261
18    0.091
19    0.167
Name: SLG, dtype: float64

##### df.loc

<p>Along the horizontal dimension, rows of Pandas DataFrames are Row objects. You will notice there is a third column present in the DataFrame - this is the $\textit{index}$. It is automatically generated as a row number, but can be reassigned to a column of your choice using the DataFrame.set_index(colname) method. We can use it to access particular Pandas $\textit{rows}$, which are also Series objects:</p>

In [ ]:
df1.set_index('SLG')

,"""﻿Rk",Pos,Name,Age,G,PA,AB,R,H,2B,...,BA,OBP,OPS,OPS+,TB,GDP,HBP,SH,SF,"IBB"""
SLG,,,,,,,,,,,,,,,,,,,,,
0.279,"""1",C,Sandy Leon,29,89,288,265,30,47,12,...,0.177,0.232,0.511,37,74,6,4,3,1,"0"""
0.433,"""2",1B,Mitch Moreland,32,124,459,404,57,99,23,...,0.245,0.325,0.758,102,175,12,0,0,5,"2"""
0.388,"""3",2B,Eduardo Nunez,31,127,502,480,56,127,23,...,0.265,0.289,0.677,81,186,17,2,1,3,"0"""
0.522,"""4",SS,Xander Bogaerts,25,136,580,513,72,148,45,...,0.288,0.360,0.883,135,268,14,6,0,6,"4"""
0.433,"""5",3B,Rafael Devers,21,121,490,450,59,108,24,...,0.240,0.298,0.731,94,195,9,0,0,2,"6"""
0.465,"""6",LF,Andrew Benintendi,23,148,661,579,103,168,41,...,0.290,0.366,0.830,123,269,9,2,2,7,"1"""
0.403,"""7",CF,Jackie Bradley Jr.,28,144,535,474,76,111,33,...,0.234,0.314,0.717,92,191,6,11,0,4,"3"""
0.640,"""8",RF,Mookie Betts,25,136,614,520,129,180,47,...,0.346,0.438,1.078,186,333,5,8,0,5,"8"""
0.629,"""9",DH,J.D. Martinez,30,150,649,569,111,188,37,...,0.330,0.402,1.031,173,358,19,4,0,7,"11"""
0.411,"""10",MI,Brock Holt,30,109,367,321,41,89,18,...,0.277,0.362,0.774,109,132,7,7,0,2,"2"""
0.283,"""11",C,Christian Vazquez,27,80,269,251,24,52,10,...,0.207,0.257,0.540,46,71,5,4,1,0,"1"""
0.328,"""12",UT,Blake Swihart,26,82,207,192,28,44,10,...,0.229,0.285,0.613,65,63,4,0,0,0,"0"""
0.395,"""13",UT,Hanley Ramirez,34,44,195,177,25,45,7,...,0.254,0.313,0.708,90,70,9,2,0,2,"0"""
0.507,"""14",1B,Steve Pearce,35,50,165,136,19,38,8,...,0.279,0.394,0.901,141,69,1,5,0,2,"0"""
0.311,"""15",2B,Ian Kinsler,36,37,143,132,17,32,6,...,0.242,0.294,0.604,64,41,5,0,0,1,"0"""
0.415,"""16",SS,Tzu-Wei Lin,24,37,73,65,15,16,6,...,0.246,0.329,0.744,100,27,0,0,0,0,"0"""
0.389,"""17",UT,Sam Travis,24,19,38,36,5,8,3,...,0.222,0.263,0.652,73,14,1,0,0,0,"0"""
0.261,"""18",UT,Brandon Phillips,37,9,27,23,4,3,0,...,0.130,0.259,0.520,42,6,1,0,0,0,"0"""
0.091,"""19",2B,Dustin Pedroia,34,3,13,11,1,1,0,...,0.091,0.231,0.322,-7,1,0,0,0,0,"0"""
0.167,"""20",C,Dan Butler,31,2,7,6,0,1,0,...,0.167,0.143,0.310,-17,1,0,0,0,1,"0"""

##### keys()

In [ ]:
# Access all of the keys/columns of the dataframe
# Dataframe.keys()
df1.keys()

Index(['"﻿Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B',
       'HR', 'RBI', 'SB', 'CS', 'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+',
       'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB"'],
      dtype='object')

##### Slicing a DataFrame

In [ ]:
# printing all data for context
df1.iloc[:,2:6]

                  Name  Age    G   PA
0           Sandy Leon   29   89  288
1       Mitch Moreland   32  124  459
2        Eduardo Nunez   31  127  502
3      Xander Bogaerts   25  136  580
4        Rafael Devers   21  121  490
5    Andrew Benintendi   23  148  661
6   Jackie Bradley Jr.   28  144  535
7         Mookie Betts   25  136  614
8        J.D. Martinez   30  150  649
9           Brock Holt   30  109  367
10   Christian Vazquez   27   80  269
11       Blake Swihart   26   82  207
12      Hanley Ramirez   34   44  195
13        Steve Pearce   35   50  165
14         Ian Kinsler   36   37  143
15         Tzu-Wei Lin   24   37   73
16          Sam Travis   24   19   38
17    Brandon Phillips   37    9   27
18      Dustin Pedroia   34    3   13
19          Dan Butler   31    2    7

### Built-In Methods <br>

<p>These are methods that are frequently used when using Pandas to make your life easier. It is possible to spend a whole week simply exploring the built-in functions supported by DataFrames in Pandas. Here however, we will simply highlight a few ones that might be useful, to give you an idea of what's possible out of the box with Pandas:</p>

##### head()

In [ ]:
# DataFrame.head()  -- Accepts integer parameter(gives access to more rows)
df1.head()

,"""﻿Rk",Pos,Name,Age,G,PA,AB,R,H,2B,...,OBP,SLG,OPS,OPS+,TB,GDP,HBP,SH,SF,"IBB"""
0,"""1",C,Sandy Leon,29,89,288,265,30,47,12,...,0.232,0.279,0.511,37,74,6,4,3,1,"0"""
1,"""2",1B,Mitch Moreland,32,124,459,404,57,99,23,...,0.325,0.433,0.758,102,175,12,0,0,5,"2"""
2,"""3",2B,Eduardo Nunez,31,127,502,480,56,127,23,...,0.289,0.388,0.677,81,186,17,2,1,3,"0"""
3,"""4",SS,Xander Bogaerts,25,136,580,513,72,148,45,...,0.360,0.522,0.883,135,268,14,6,0,6,"4"""
4,"""5",3B,Rafael Devers,21,121,490,450,59,108,24,...,0.298,0.433,0.731,94,195,9,0,0,2,"6"""

##### tail()

In [ ]:
# DataFrame.tail()  -- Accepts integer parameter(gives access to more rows)
df1.tail()

,"""﻿Rk",Pos,Name,Age,G,PA,AB,R,H,2B,...,OBP,SLG,OPS,OPS+,TB,GDP,HBP,SH,SF,"IBB"""
15,"""16",SS,Tzu-Wei Lin,24,37,73,65,15,16,6,...,0.329,0.415,0.744,100,27,0,0,0,0,"0"""
16,"""17",UT,Sam Travis,24,19,38,36,5,8,3,...,0.263,0.389,0.652,73,14,1,0,0,0,"0"""
17,"""18",UT,Brandon Phillips,37,9,27,23,4,3,0,...,0.259,0.261,0.520,42,6,1,0,0,0,"0"""
18,"""19",2B,Dustin Pedroia,34,3,13,11,1,1,0,...,0.231,0.091,0.322,-7,1,0,0,0,0,"0"""
19,"""20",C,Dan Butler,31,2,7,6,0,1,0,...,0.143,0.167,0.310,-17,1,0,0,0,1,"0"""

##### shape

In [ ]:
# The dataframe has a shape property, just like a NumPy matrix.
# print(df.shape) -- DataFrame.shape -- No Parameter


df1.shape

(20, 28)

##### describe() <br>
<p>Probably one of the most important methods to understand...</p>

In [ ]:
# Collect summary statistics in one line
# DataFrame.describe() -- Accepts parameters (include, exclude)
df1.describe()

,Age,G,PA,AB,R,H,2B,3B,HR,RBI,...,BA,OBP,SLG,OPS,OPS+,TB,GDP,HBP,SH,SF
count,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,...,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000
mean,29.100000,82.350000,314.100000,280.200000,43.600000,75.250000,17.650000,1.550000,10.400000,41.300000,...,0.237950,0.307700,0.387500,0.695200,86.450000,127.200000,6.500000,2.750000,0.350000,2.400000
std,4.666792,52.916294,230.972065,203.871631,38.293053,62.462515,15.624795,1.959457,11.722224,37.559917,...,0.061985,0.068843,0.135884,0.200419,52.199491,113.226183,5.633546,3.274704,0.812728,2.436564
min,21.000000,2.000000,7.000000,6.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,...,0.091000,0.143000,0.091000,0.310000,-17.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,25.000000,37.000000,125.500000,115.250000,16.500000,28.000000,6.000000,0.000000,1.000000,13.750000,...,0.218250,0.262000,0.304000,0.588000,59.500000,37.500000,1.000000,0.000000,0.000000,0.000000
50%,29.500000,85.500000,278.500000,258.000000,29.000000,49.500000,11.000000,0.500000,6.500000,27.500000,...,0.243500,0.305500,0.399000,0.712500,91.000000,72.500000,5.500000,2.000000,0.000000,2.000000
75%,32.500000,129.250000,510.250000,475.500000,62.250000,115.000000,26.250000,3.000000,15.250000,66.500000,...,0.277500,0.360500,0.441000,0.788000,112.500000,192.000000,9.000000,4.250000,0.000000,4.250000
max,37.000000,150.000000,661.000000,579.000000,129.000000,188.000000,47.000000,6.000000,43.000000,130.000000,...,0.346000,0.438000,0.640000,1.078000,186.000000,358.000000,19.000000,11.000000,3.000000,7.000000

##### sort_values()

In [ ]:
# Sort based on many labels, with left-to-right priority
# sorted_data = data.sort_values('ages').reset_index()

# DataFrame.sort_values('key')

df1.sort_values('Age').reset_index()

,index,"""﻿Rk",Pos,Name,Age,G,PA,AB,R,H,...,OBP,SLG,OPS,OPS+,TB,GDP,HBP,SH,SF,"IBB"""
0,4,"""5",3B,Rafael Devers,21,121,490,450,59,108,...,0.298,0.433,0.731,94,195,9,0,0,2,"6"""
1,5,"""6",LF,Andrew Benintendi,23,148,661,579,103,168,...,0.366,0.465,0.830,123,269,9,2,2,7,"1"""
2,16,"""17",UT,Sam Travis,24,19,38,36,5,8,...,0.263,0.389,0.652,73,14,1,0,0,0,"0"""
3,15,"""16",SS,Tzu-Wei Lin,24,37,73,65,15,16,...,0.329,0.415,0.744,100,27,0,0,0,0,"0"""
4,3,"""4",SS,Xander Bogaerts,25,136,580,513,72,148,...,0.360,0.522,0.883,135,268,14,6,0,6,"4"""
5,7,"""8",RF,Mookie Betts,25,136,614,520,129,180,...,0.438,0.640,1.078,186,333,5,8,0,5,"8"""
6,11,"""12",UT,Blake Swihart,26,82,207,192,28,44,...,0.285,0.328,0.613,65,63,4,0,0,0,"0"""
7,10,"""11",C,Christian Vazquez,27,80,269,251,24,52,...,0.257,0.283,0.540,46,71,5,4,1,0,"1"""
8,6,"""7",CF,Jackie Bradley Jr.,28,144,535,474,76,111,...,0.314,0.403,0.717,92,191,6,11,0,4,"3"""
9,0,"""1",C,Sandy Leon,29,89,288,265,30,47,...,0.232,0.279,0.511,37,74,6,4,3,1,"0"""
10,9,"""10",MI,Brock Holt,30,109,367,321,41,89,...,0.362,0.411,0.774,109,132,7,7,0,2,"2"""
11,8,"""9",DH,J.D. Martinez,30,150,649,569,111,188,...,0.402,0.629,1.031,173,358,19,4,0,7,"11"""
12,2,"""3",2B,Eduardo Nunez,31,127,502,480,56,127,...,0.289,0.388,0.677,81,186,17,2,1,3,"0"""
13,19,"""20",C,Dan Butler,31,2,7,6,0,1,...,0.143,0.167,0.310,-17,1,0,0,0,1,"0"""
14,1,"""2",1B,Mitch Moreland,32,124,459,404,57,99,...,0.325,0.433,0.758,102,175,12,0,0,5,"2"""
15,12,"""13",UT,Hanley Ramirez,34,44,195,177,25,45,...,0.313,0.395,0.708,90,70,9,2,0,2,"0"""
16,18,"""19",2B,Dustin Pedroia,34,3,13,11,1,1,...,0.231,0.091,0.322,-7,1,0,0,0,0,"0"""
17,13,"""14",1B,Steve Pearce,35,50,165,136,19,38,...,0.394,0.507,0.901,141,69,1,5,0,2,"0"""
18,14,"""15",2B,Ian Kinsler,36,37,143,132,17,32,...,0.294,0.311,0.604,64,41,5,0,0,1,"0"""
19,17,"""18",UT,Brandon Phillips,37,9,27,23,4,3,...,0.259,0.261,0.520,42,6,1,0,0,0,"0"""

##### .columns

In [ ]:
# will show all cols headers
# DataFrame.columns -- has no parameters


# Keys brings back the 'index' of whatever data type we are working with
df1.columns

Index(['"﻿Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B',
       'HR', 'RBI', 'SB', 'CS', 'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+',
       'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB"'],
      dtype='object')

### In-Class Exercise #2 - Describe & Sort Boston Red Sox Hitting Data <br>
<p>Take the data that you read in earlier from the Red Sox csv's and use the describe method to understand the data better. Compare the two years and decide which team is having the better year. Then sort the values based on Batting Average.</p>

In [ ]:
df1.describe()
df1.sort_values('BA').iloc[:,6:23]

,AB,R,H,2B,3B,HR,RBI,SB,CS,BB,SO,BA,OBP,SLG,OPS,OPS+,TB
18,11,1,1,0,0,0,0,0,0,2,1,0.091,0.231,0.091,0.322,-7,1
17,23,4,3,0,0,1,2,0,0,4,7,0.130,0.259,0.261,0.520,42,6
19,6,0,1,0,0,0,1,0,0,0,2,0.167,0.143,0.167,0.310,-17,1
0,265,30,47,12,0,5,22,1,0,15,75,0.177,0.232,0.279,0.511,37,74
10,251,24,52,10,0,3,16,4,1,13,41,0.207,0.257,0.283,0.540,46,71
16,36,5,8,3,0,1,7,0,0,2,10,0.222,0.263,0.389,0.652,73,14
11,192,28,44,10,0,3,18,6,1,15,57,0.229,0.285,0.328,0.613,65,63
6,474,76,111,33,4,13,59,17,1,46,137,0.234,0.314,0.403,0.717,92,191
4,450,59,108,24,0,21,66,5,2,38,121,0.240,0.298,0.433,0.731,94,195
14,132,17,32,6,0,1,16,7,3,10,24,0.242,0.294,0.311,0.604,64,41
1,404,57,99,23,4,15,68,2,0,50,102,0.245,0.325,0.433,0.758,102,175
15,65,15,16,6,1,1,6,0,1,8,17,0.246,0.329,0.415,0.744,100,27
12,177,25,45,7,0,6,29,4,1,14,35,0.254,0.313,0.395,0.708,90,70
2,480,56,127,23,3,10,44,7,2,16,69,0.265,0.289,0.388,0.677,81,186
9,321,41,89,18,2,7,46,7,7,37,73,0.277,0.362,0.411,0.774,109,132
13,136,19,38,8,1,7,26,0,0,22,27,0.279,0.394,0.507,0.901,141,69
3,513,72,148,45,3,23,103,8,2,55,102,0.288,0.360,0.522,0.883,135,268
5,579,103,168,41,6,16,87,21,3,71,106,0.290,0.366,0.465,0.830,123,269
8,569,111,188,37,2,43,130,6,1,69,146,0.330,0.402,0.629,1.031,173,358
7,520,129,180,47,5,32,80,30,6,81,91,0.346,0.438,0.640,1.078,186,333

In [ ]:
df2.describe()

df2.sort_values('BA').iloc[:,6:23]

,AB,R,H,2B,3B,HR,RBI,SB,CS,BB,SO,BA,OBP,SLG,OPS,OPS+,TB
20,9,0,1,1,0,0,0,0,0,0,5,0.111,0.111,0.222,0.333,-16,2
13,140,20,28,6,0,0,7,2,1,19,34,0.200,0.305,0.243,0.548,47,34
21,5,1,1,0,0,0,0,0,0,2,3,0.200,0.429,0.200,0.629,74,1
11,171,32,36,9,0,4,27,5,0,12,61,0.211,0.259,0.333,0.593,54,57
15,99,10,21,2,0,4,12,0,1,8,24,0.212,0.269,0.354,0.622,61,35
14,107,10,24,2,1,0,9,1,0,9,31,0.224,0.297,0.262,0.558,49,28
9,271,32,61,14,0,7,39,0,0,25,74,0.225,0.290,0.354,0.644,68,96
10,243,30,57,12,2,7,25,3,2,30,55,0.235,0.322,0.387,0.709,85,94
8,496,58,120,24,0,23,62,1,3,51,116,0.242,0.320,0.429,0.750,94,213
6,482,58,118,19,3,17,63,8,3,48,124,0.245,0.323,0.402,0.726,89,194
1,508,73,125,34,0,22,79,0,1,57,120,0.246,0.326,0.443,0.769,99,225
19,36,7,9,2,0,0,2,3,1,1,13,0.250,0.289,0.306,0.595,56,11
16,76,13,20,6,0,0,1,1,0,6,23,0.263,0.325,0.342,0.667,75,26
7,628,101,166,46,2,24,102,26,3,77,79,0.264,0.344,0.459,0.803,108,288
17,56,7,15,0,2,0,2,1,1,9,17,0.268,0.369,0.339,0.709,88,19
5,573,84,155,26,1,20,90,20,5,70,112,0.271,0.352,0.424,0.776,102,243
3,571,94,156,32,6,10,62,15,1,56,116,0.273,0.343,0.403,0.746,95,230
18,58,7,16,3,0,0,2,0,1,1,15,0.276,0.300,0.328,0.628,65,19
4,222,34,63,14,0,10,30,3,1,18,57,0.284,0.338,0.482,0.819,111,107
0,324,43,94,18,2,5,32,7,2,17,64,0.290,0.330,0.404,0.735,91,131
2,406,46,119,19,0,7,62,4,3,49,48,0.293,0.369,0.392,0.760,100,159
12,165,23,53,12,0,8,27,6,2,6,25,0.321,0.353,0.539,0.892,128,89
22,1,2,1,0,0,0,0,0,0,0,0,1.000,1.000,1.000,2.000,428,1

### Filtration <br>
<p>Let's look at how to filter dataframes for rows that fulfill a specific conditon.</p>

##### Conditionals

In [ ]:
# Conditional boolean dataframe
df1[df1['Age']>20]

,"""﻿Rk",Pos,Name,Age,G,PA,AB,R,H,2B,...,OBP,SLG,OPS,OPS+,TB,GDP,HBP,SH,SF,"IBB"""
0,"""1",C,Sandy Leon,29,89,288,265,30,47,12,...,0.232,0.279,0.511,37,74,6,4,3,1,"0"""
1,"""2",1B,Mitch Moreland,32,124,459,404,57,99,23,...,0.325,0.433,0.758,102,175,12,0,0,5,"2"""
2,"""3",2B,Eduardo Nunez,31,127,502,480,56,127,23,...,0.289,0.388,0.677,81,186,17,2,1,3,"0"""
3,"""4",SS,Xander Bogaerts,25,136,580,513,72,148,45,...,0.360,0.522,0.883,135,268,14,6,0,6,"4"""
4,"""5",3B,Rafael Devers,21,121,490,450,59,108,24,...,0.298,0.433,0.731,94,195,9,0,0,2,"6"""
5,"""6",LF,Andrew Benintendi,23,148,661,579,103,168,41,...,0.366,0.465,0.830,123,269,9,2,2,7,"1"""
6,"""7",CF,Jackie Bradley Jr.,28,144,535,474,76,111,33,...,0.314,0.403,0.717,92,191,6,11,0,4,"3"""
7,"""8",RF,Mookie Betts,25,136,614,520,129,180,47,...,0.438,0.640,1.078,186,333,5,8,0,5,"8"""
8,"""9",DH,J.D. Martinez,30,150,649,569,111,188,37,...,0.402,0.629,1.031,173,358,19,4,0,7,"11"""
9,"""10",MI,Brock Holt,30,109,367,321,41,89,18,...,0.362,0.411,0.774,109,132,7,7,0,2,"2"""
10,"""11",C,Christian Vazquez,27,80,269,251,24,52,10,...,0.257,0.283,0.540,46,71,5,4,1,0,"1"""
11,"""12",UT,Blake Swihart,26,82,207,192,28,44,10,...,0.285,0.328,0.613,65,63,4,0,0,0,"0"""
12,"""13",UT,Hanley Ramirez,34,44,195,177,25,45,7,...,0.313,0.395,0.708,90,70,9,2,0,2,"0"""
13,"""14",1B,Steve Pearce,35,50,165,136,19,38,8,...,0.394,0.507,0.901,141,69,1,5,0,2,"0"""
14,"""15",2B,Ian Kinsler,36,37,143,132,17,32,6,...,0.294,0.311,0.604,64,41,5,0,0,1,"0"""
15,"""16",SS,Tzu-Wei Lin,24,37,73,65,15,16,6,...,0.329,0.415,0.744,100,27,0,0,0,0,"0"""
16,"""17",UT,Sam Travis,24,19,38,36,5,8,3,...,0.263,0.389,0.652,73,14,1,0,0,0,"0"""
17,"""18",UT,Brandon Phillips,37,9,27,23,4,3,0,...,0.259,0.261,0.520,42,6,1,0,0,0,"0"""
18,"""19",2B,Dustin Pedroia,34,3,13,11,1,1,0,...,0.231,0.091,0.322,-7,1,0,0,0,0,"0"""
19,"""20",C,Dan Butler,31,2,7,6,0,1,0,...,0.143,0.167,0.310,-17,1,0,0,0,1,"0"""

##### Subsetting

In [ ]:
# exactly like numpy
df1[['Age','BA','SLG']]

    Age     BA    SLG
0    29  0.177  0.279
1    32  0.245  0.433
2    31  0.265  0.388
3    25  0.288  0.522
4    21  0.240  0.433
5    23  0.290  0.465
6    28  0.234  0.403
7    25  0.346  0.640
8    30  0.330  0.629
9    30  0.277  0.411
10   27  0.207  0.283
11   26  0.229  0.328
12   34  0.254  0.395
13   35  0.279  0.507
14   36  0.242  0.311
15   24  0.246  0.415
16   24  0.222  0.389
17   37  0.130  0.261
18   34  0.091  0.091
19   31  0.167  0.167

In [ ]:
%pip install faker

Collecting faker
  Downloading Faker-24.9.0-py3-none-any.whl (1.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 7.3 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.4 in /usr/local/lib/python3.10/dist-packages (from faker) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.4->faker) (1.16.0)
Installing collected packages: faker
Successfully installed faker-24.9.0

### Column Transformations <br>
<p>Rarely, if ever, will the columns in the original raw dataframe read from CSV or database table be the ones you actually need for your analysis. You will spend lots of time constantly transforming columns or groups of columns using general computational operations to produce new ones that are functions of the old ones. Pandas has full support for this: Consider the following dataframe containing membership term and renewal number for a group of customers:</p>

In [ ]:
import pandas as pd
from faker import Faker

# Set up Faker for generating fake data
fake = Faker()

# Number of rows in the dataset
num_rows = 10
# Generate fake data for the three columns
data = {
    'Renewal Number': ['R' + str(i) for i in range(1, num_rows + 1)],
    'Customer ID': ['C' + str(i) for i in range(1001, 1001 + num_rows)],
    'Membership Term': [fake.random_element(elements=(3, 6, 9, 12, 18, 24)) for _ in range(num_rows)]
}
# Create a DataFrame
df = pd.DataFrame(data)

# Display the generated DataFrame
print(df)

  Renewal Number Customer ID  Membership Term
0             R1       C1001                9
1             R2       C1002                9
2             R3       C1003               12
3             R4       C1004                3
4             R5       C1005                3
5             R6       C1006                3
6             R7       C1007                3
7             R8       C1008               24
8             R9       C1009               24
9            R10       C1010                6

##### Generating a New Column w/Data

In [ ]:
# DataFrame['key'] = Some Calculation from our DataFrame Columns
df['Days']=df['Membership Term']*30
df

  Renewal Number Customer ID  Membership Term  Days
0             R1       C1001                9   270
1             R2       C1002                9   270
2             R3       C1003               12   360
3             R4       C1004                3    90
4             R5       C1005                3    90
5             R6       C1006                3    90
6             R7       C1007                3    90
7             R8       C1008               24   720
8             R9       C1009               24   720
9            R10       C1010                6   180

##### User Defined Function

<p>If what you want to do to a column that can't be represented by simple mathematical operations, you can write your own $\textit{user defined function}$ with the full customizability available in Python and any external Python packages, then map it directly onto a column. Let's add some ages to our customer dataframe, and then classify them into our custom defined grouping scheme:</p>

In [ ]:
# use .apply to map over dataframe

# Create a new column for ages
# customers['ages'] = np.random.randint(18,70,10)

# User defined function


# print(make_age_groups)

def mem_convert(x):
  if x<10:
    return 'cat1'
  else:
    return 'cat2'

df['mem_cat'] = df['Membership Term'].apply(mem_convert)
df

  Renewal Number Customer ID  Membership Term  Days mem_cat
0             R1       C1001                9   270    cat1
1             R2       C1002                9   270    cat1
2             R3       C1003               12   360    cat2
3             R4       C1004                3    90    cat1
4             R5       C1005                3    90    cat1
5             R6       C1006                3    90    cat1
6             R7       C1007                3    90    cat1
7             R8       C1008               24   720    cat2
8             R9       C1009               24   720    cat2
9            R10       C1010                6   180    cat1

<p>As a last example I'll show here how you would use a lambda function to create a UDF that depends on $\textit{more than one}$ column:</p>

<li>UDF = User Defined Function</li>

In [ ]:
#Axis for apply can only be 1 or 0 -- 1 being the X axis 0 being the Y axis

### In-Class Exercise #3 - Create Your Own UDF <br>
<p>Using the Boston Red Sox data, create your own UDF which creates a new column called 'All-Star' and puts every player with either a batting average over .280 or an on base percentage of over .360 with a result of 'Yes' in the column and 'No' if not.</p>

In [ ]:
"""
    Name  BA OBP AllStar
    --------------------
    Name .233 .360 Yes
    Name .150 .288 No
"""
df1.columns

Index(['"﻿Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B',
       'HR', 'RBI', 'SB', 'CS', 'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+',
       'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB"'],
      dtype='object')

In [ ]:
def ba(x):
  if x<0.280 :
    return 'No'
  else:
    return 'Yes'

df1['All-Star'] = df1['BA'].apply(ba)

In [ ]:
df1[['Name','BA','OBP','All-Star']].head()

              Name     BA    OBP All-Star
0       Sandy Leon  0.177  0.232       No
1   Mitch Moreland  0.245  0.325       No
2    Eduardo Nunez  0.265  0.289       No
3  Xander Bogaerts  0.288  0.360      Yes
4    Rafael Devers  0.240  0.298       No

### Aggregations <br>
<p>The raw data plus some transformations is generally only half the story. Your objective is to extract actual insights and actionable conclusions from the data, and that means reducing it from potentially billions of rows to some summary statistics via aggregation functions.</p>

##### groupby() <br>
<p>The .groupby() function is in some ways a 'master' aggregation.</p>

<p>Data tables will usually reserve one column as a primary key - that is, a column for which each row has a unique value. This is to facilitate access to the exact rows of a data table that a user wants to view. The other columns will often have repeated values, such as the age groups in the above examples. We can use these columns to explore the data using the Pandas API:</p>

In [ ]:
# also introducing .count() here, exact same as to how it's used in SQL

# Using the groupby with the column intact as a column/key
# customers.groupby('age_group', as_index = False).count()[['customer_id','age_group']]


df.groupby([''])

  Renewal Number Customer ID  Membership Term  Days mem_cat
0             R1       C1001                9   270    cat1
1             R2       C1002                9   270    cat1
2             R3       C1003               12   360    cat2
3             R4       C1004                3    90    cat1
4             R5       C1005                3    90    cat1
5             R6       C1006                3    90    cat1
6             R7       C1007                3    90    cat1
7             R8       C1008               24   720    cat2
8             R9       C1009               24   720    cat2
9            R10       C1010                6   180    cat1

##### Type of groupby()

<p>The result is a new dataframe, the columns of which all contain the counts of the grouped field. Notice the type of a grouped dataframe:</p>

<p>This is because simply grouping data doesn't quite make sense without an aggregation function like count() to pair with. In this case, we're counting occurances of the grouped field, but that's not all we can do. We can take averages, standard deviations, mins, maxes and much more! Let's see how this works a bit more:</p>

##### mean()

In [ ]:
# mean = average

##### groupby() w/Multiple Columns

<p>We end up with the average age of the groups in the last column, the average tenure in the tenure column, and so on and so forth. You can even split the groups more finely by passing a list of columns to group by:</p>

##### drop_duplicates()

<p>Drops all duplicates from the current dataframe</p>

In [ ]:
# Send customer data into a CSV file

<p>Thus the groupby operation allows you to rapidly make summary observations about the state of your entire dataset at flexible granularity. In one line above, we actually did something very complicated - that's the power of the dataframe. In fact, the process often consists of several iterative groupby operations, each revealing greater insight than the last - if you don't know where to start with a dataset, try a bunch of groupbys!</p>

### Homework Excersise #1 - Find the Total Number of Runs and RBIs for the Red Sox <br>
<p>Get total number of home runs and rbi's</p>

In [ ]:
# step 1: Add a new column with the key 'Team' and all column values should be 'BOS'

# step 2: Group by the 'Team' column and get total home runs and rbi's

# Produce data for both 2017 and 2018 (ie print both seperated by a newline character \n)

"""
TEAM    HR   RBI
----------------
BOS     144  538
"""

df1['Team'] = 'BOS'

df1.groupby(['Team'])[['HR','RBI']].sum()

       HR  RBI
Team
BOS   208  826

In [ ]:
df2['Team'] = 'BOS'

df2.groupby(['Team'])[['HR','RBI']].sum()

       HR  RBI
Team
BOS   168  735

## Find the average age of runners in the 2017 Boston Marathon

In [ ]:
df1['Age'].mean()

29.1

In [ ]:
df2['Age'].mean()

27.47826086956522